### PR TITLE
Posix compliance for install.sh

### PR DESCRIPTION
**Pull request by maaslalani**
This PR removes "bashism"s from the `install.sh` script to make it posix compliant.

Using shellcheck, I removed the bash-specific code parts which mainly included:
- Removing use of `function`
- Removing use of `local`
- Not using `[[ ... ]]` or `(( ... ))` (prefer `test`)

NB: I have not tested this code to see if it works since I don't have `tea` installed.

### CODE REVIEW

**Comment by mxcl** [comment]
amazing thank you!

PR won’t pass yet due to `TEA_SECRET` being a GitHub secret. But I'm hoping we can relax that this coming week.

**Comment by maaslalani** [comment]
Oops, didn't know deleting my fork would close the PR

**Comment by mxcl** [comment]
@maaslalani unfortunately, (apparently) without your fork I cannot merge.

We are passing now though!

**Comment by mxcl** [comment]
If you can't recover it then either you or me can get the diff (it's still here).

I'd rather it was you so you get the credit.

**Comment by maaslalani** [comment]
Cool yeah just forking the repo now!

**Comment by maaslalani** [comment]
Let me know if you can merge this one, if not I made a separate pull request: https://github.com/teaxyz/setup/pull/60

**Comment by maaslalani** [comment]
Note to self, don't delete forks prematurely 😄

**Comment by mxcl** [comment]
Yeah that helped. But for some reason I cannot push the conflict resolution to your fork this time. So I resolved it in #60 instead. Closing this one.

**Comment by maaslalani** [comment]
Sweet, thanks for that!

**Pull request closed without merging**
