### PR TITLE
use gz with fallback to xz

### PR DESCRIPTION
**Pull request by jhheider**

### CODE REVIEW

**Comment by mxcl** [comment]
I'm squeamish about this.

The installer absolutely cannot fail, and the difference is ~6MB.

**Comment by jhheider** [comment]
> The installer absolutely cannot fail, and the difference is ~6MB.

You can switch the preference order easily enough. This should make the installer more robust, since it gets two tries.

**Comment by mxcl** [comment]
I'm going to pass.

It's not worth it for 6MB.

eg. they may not be able to uncompress xz so they'll download twice. gz is the standard. tea itself can install xz so we can do this for our bottles.

**Comment by jhheider** [comment]
The problem this was intended to fix is a weird race condition:

- gha fires bottling jobs for multiple compressions
- macos-11 runners queue up
- Darwin / xz finishes, uploads the bottle _and adds the tea/cli version to versions.txt_
- Darwin / gz starts and teaxyz/setup tries to download $latest.tar.gz, but only $latest.tar.xz exists
- Darwin / gz fails, and teaxyz/setup is broken until an archive is manually uploads.

**Comment by jhheider** [comment]
Switched order of priority. But we still need to guard against that race on new builds of tea/cli

**Comment by mxcl** [comment]
How about https://github.com/teaxyz/pantry/pull/205?

**Comment by jhheider** [comment]
Worthy. In *that* case, this is _only_ needed if you desire trying the other download if the first fails.

**Comment by mxcl** [comment]
> Worthy. In that case, this is only needed if you desire trying the other download if the first fails.

Maybe one day, but I want to feel like the installer is solid-AF first.

**Pull request closed without merging**
